// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             (unknown)
// source: api/burst.proto

package api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Burst_Export_FullMethodName = "/burst/Export"
)

// BurstClient is the client API for Burst service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BurstClient interface {
	Export(ctx context.Context, in *ExportRequest, opts ...grpc.CallOption) (*ExportResponse, error)
}

type burstClient struct {
	cc grpc.ClientConnInterface
}

func NewBurstClient(cc grpc.ClientConnInterface) BurstClient {
	return &burstClient{cc}
}

func (c *burstClient) Export(ctx context.Context, in *ExportRequest, opts ...grpc.CallOption) (*ExportResponse, error) {
	out := new(ExportResponse)
	err := c.cc.Invoke(ctx, Burst_Export_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BurstServer is the server API for Burst service.
// All implementations must embed UnimplementedBurstServer
// for forward compatibility
type BurstServer interface {
	Export(context.Context, *ExportRequest) (*ExportResponse, error)
	mustEmbedUnimplementedBurstServer()
}

// UnimplementedBurstServer must be embedded to have forward compatible implementations.
type UnimplementedBurstServer struct {
}

func (UnimplementedBurstServer) Export(context.Context, *ExportRequest) (*ExportResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Export not implemented")
}
func (UnimplementedBurstServer) mustEmbedUnimplementedBurstServer() {}

// UnsafeBurstServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BurstServer will
// result in compilation errors.
type UnsafeBurstServer interface {
	mustEmbedUnimplementedBurstServer()
}

func RegisterBurstServer(s grpc.ServiceRegistrar, srv BurstServer) {
	s.RegisterService(&Burst_ServiceDesc, srv)
}

func _Burst_Export_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExportRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BurstServer).Export(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Burst_Export_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BurstServer).Export(ctx, req.(*ExportRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Burst_ServiceDesc is the grpc.ServiceDesc for Burst service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Burst_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "burst",
	HandlerType: (*BurstServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Export",
			Handler:    _Burst_Export_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/burst.proto",
}
